### ISSUE TITLE
python error when running program

### ISSUE THREAD

**Issue by egcp** [bkloppenborg/revelation-to-keepassxc#2]
Thanks for the quick fix and sorry for the long delay in responding. However, I'm running into another problem when I run your program: python revelation-xml-to-keepassxc.py passwords.xml passwords.csv

I ran it with python 2.7 on my XML file and I got the error below, and only part of the file was converted.
----
Traceback (most recent call last):
  File "revelation-xml-to-keepassxc.py", line 340, in <module>
    main()
  File "revelation-xml-to-keepassxc.py", line 337, in main
    writer.writerows(output)
  File "/usr/lib64/python2.7/csv.py", line 158, in writerows
    return self.writer.writerows(rows)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 12: ordinal not in range(128)
----

I then tried it with python 3.7 and I got this error and no file conversion.
----
Traceback (most recent call last):
  File "revelation-xml-to-keepassxc.py", line 340, in <module>
    main()
  File "revelation-xml-to-keepassxc.py", line 336, in main
    writer.writeheader()
  File "/usr/lib64/python3.7/csv.py", line 144, in writeheader
    self.writerow(header)
  File "/usr/lib64/python3.7/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
TypeError: a bytes-like object is required, not 'str'
----
Any idea on how to fix it? I tried removing password entries, but the error kept popping up.

**Comment by egcp** [comment]
The problem are special characters such as á or ^ in fields like name and notes. Any way your code can be Unicode acceptable? Thanks!

**Comment by bkloppenborg** [comment]
Odd. I can't even paste unicode characters into Revelation. I wonder if its a language pack issue? Nevertheless, could you try replacing line 23 which presently reads `import csv` with `import unicodecsv as csv` and try running it again? You may need to install the unicodecsv module using `pip install unicodecsv`. On Ubuntu you can `sudo apt install python3-unicodecsv` and then run the script with `python3` and it should work. Let me know if this works for you.

**Comment by bkloppenborg** [comment]
I just tested this locally and fixed the issue in commit 1a860f1. Unfortunately, there isn't a really clean way to fix this in code that works on both Python 2 and Python 3. So you will need to:

1. grab the latest version of the script
2. install `unicodecsv` on your system (`sudo apt install python3-unicodecsv`)
3. run the script with `python3` instead of `python`

**Comment by egcp** [comment]
Thank you! It worked like a charm.

**Comment by bkloppenborg** [comment]
I'm glad I could help. Thank you for helping me find the bugs and thank you even more for the donation!
